### ISSUE TITLE
iteration

### ISSUE THREAD

**Issue by basaran** [BlingCorp/bling#59] opened 2021-05-17 10:12 UTC
Hello,

For some reason, I'm not able to use `bling.module.tabbed.iter()` in globalkeys.

```
    awful.key({ modkey,       }, "F2", function () bling.module.tabbed.iter() end, 
              {description = "iterate through tabbing group", group = "bling"}),
```

When executed, nothing happens. No errors as well. What would be the best way to troubleshoot this?

**Comment by branwright1** [comment] 2021-05-17 13:11
Hello, have you tried other keys as well? If it's laptop then button like F1-12 might not work without FN + F1-12 because of media keys.

You may also try `xorg.xev` package through this command to check keycode for this button.
`xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'`

**Comment by Nooo37** [comment] 2021-05-17 19:02
1. Try to find out whether the keybind works by replacing `bling.module.tabbed.iter()` with `require("naughty").notify({title="yea, it works"})`. If it does work you should see the notification pop up. I would think that's the most likely since you didn't get any error messages. 
2. If the keybind does work, try whether the `iter` function works by using `awesome-client`. I assume you can create a tab group? Do that and put `sleep 5; awesome-client 'require("bling").module.tabbed.iter()'` in a terminal and then switch within the sleep time to your tab group and watch whether or not the function works or what error message it might put into your command line.
3. If both steps succeeded, you might want to check for trivial errors such as whether you imported bling in the file that adds this keybind. Also consider to upload the whole file or rc.lua so we can inspect further if you haven't had any success.

**Comment by basaran** [comment] 2021-05-18 19:21
Hello, thank you both for getting back. I made sure it's not an issue with the F2 being an fn key. I got the notification from naugty. Please see the recording.

https://user-images.githubusercontent.com/30809170/118710558-74857400-b7ec-11eb-858e-06ba9a1a11d8.mp4

I suspect this might be related to some other libraries I'm using (collision from elv13).

P.S I will do a clean up on my config and then upload it as well.

**Comment by branwright1** [comment] 2021-05-18 20:30
I don't think collision is conflicting, we have tested tabs with collision and other external modules and it was working without any problems. Have you tried reinstalling bling? also if you call keybinds from e.g. `keybinds.lua` then bling must be required in this file as well.

**Comment by basaran** [comment] 2021-05-18 23:27
Hello, I tried with a stock `rc.lua`, a fresh `bling` cloned into it, required it, assigned the mstab layout and it still didn't work. Mysterious :) 

I tested with the `sleep 5; awesome-client 'require("bling").module.tabbed.iter()'` you gave me. Result was the same as in video, like nothing happens. I will keep looking into this and update here when I get it to work.

You don't think it's my kernel or anything, right?

```
Linux ala-arch 5.12.0-1-ck-zen #1 SMP PREEMPT Wed, 28 Apr 2021 10:51:19 +0000 x86_64 GNU/Linux
```

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Comment by branwright1** [comment] 2021-05-18 23:34
Kernel has nothing to do with your WM. Thats really weird issue, all what you need is `xwininfo` package according to our readne.

**Comment by basaran** [comment] 2021-05-18 23:46
I already have it `xwininfo`

```
xwininfo -version
xwininfo 1.1.5
```
I will get back to it this weekend, please keep the ticket open until then.

**Comment by Nooo37** [comment] 2021-05-19 06:10
So the problem is that you seem to use the `iter` function on the mstab layout. That is surely confusing but we got a layout called `mstab` that is just a normal dynamic master stack layout that looks like its tabbing the stack side of its layout and we got the module `tabbed` that creates tabbing groups that you can use in whatever layout you want to. On the mstab layout you can only iter through the clients with your normal mod+tab or any other keybind that iters through every client while in the actual tabbing groups of the tabbed module you can use the `iter` function. 
What I mean is that `bling.module.tabbed.iter()` only works on tab groups that got created with `bling.module.tabbed.pick_with_dmenu()` or something similar. Here is the documentation for the tabbing groups: https://blingcorp.github.io/bling/#/module/tabbed while the mstab layout is only mentioned in the layout section https://blingcorp.github.io/bling/#/layouts/layout.

**Comment by Piterden** [comment] 2021-05-19 11:23
I think the problem is caused by hiding of tabs placed lower the master in a tab group. How do you think, maybe we can use the stacked layout for placing tabs under each other without hiding them from taskbar?

**Comment by basaran** [comment] 2021-05-19 19:47
that solved the mystery) I was under the impression the `stack` was the `tab` which it is not. I have been using the `cyclefocus` module for alt-tab, could you please let me know if there is a recommended switcher to be used with `bling`?

**Comment by Piterden** [comment] 2021-05-20 07:39
I use this for alt-tab https://github.com/sagb/alttab.

Try to use `.iter(-1)` to move back.

**Comment by Piterden** [comment] 2021-05-20 15:30
I just noticed that bling commands are not working if you use a separated require in the key-bindings file. Maybe it is better to use a function for init functionality?

**Comment by basaran** [comment] 2021-05-20 18:07
Thank you for the `alttab` link Piterden. I'm not sure about the separated require for bling, I just have a require in my init.lua and it seems to be accessible fine from my globalkeys.lua. 

At the risk of ticket going off topic, can the `tab groups` be used with `floating` windows? It sometimes work, but if you switch clients with dedicated shortcuts instead of clicking with mouse, it's creating duplicated clones the tabbed clients. I can create a separate ticket with a video for you to see.

**Comment by HeavyRain266** [comment] 2021-05-20 18:15
> At the risk of ticket going off topic, can the tab groups be used with floating windows?

yes, you can do it, thats what I'm using all the time now. Duplicating clients is know problem at least for me, it's good idea to just ope new issue and we will try to fix as fast as possible but I will be not surprised if it will take some time because May/June usually are ending for school years in most countries so a lot of exams etc.

**Comment by Piterden** [comment] 2021-05-20 18:36
@basaran Does you `globalkeys.lua` file has own require of bling?

**Comment by Nooo37** [comment] 2021-05-20 19:05
@basaran Regarding your second paragraph: That surely shouldn't happen. There shouldn't be a difference between performing the action through the shortcut or through a mouse click. If you can reproduce that in a video, that would be cool and you should open another issue for that :+1:

Apart from that, the inital question has been solved right? Because if so, I would close the issue.

**Comment by HeavyRain266** [comment] 2021-05-20 19:11
We should create general discussion for bling or link awesome discord in readme. From waht I saw it's solved so I'm closing this issue

**Closed** 2021-05-20 19:12 UTC
Labels: help wanted
